### PR TITLE
Moving from DDKalTestConf to LCTrackerConf

### PR DESCRIPTION
**Pull request by eleogran**
BEGINRELEASENOTES
- DDKalTestConf replaced by LCTrackerConf

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
You should also remove the file `DDKalTestConf.h`

**Comment by eleogran** [comment]
Done

**Comment by andresailer** [comment]
I wanted to make this comment https://github.com/iLCSoft/MarlinTrkProcessors/pull/9#issuecomment-291792922 here.
Wait for these pull requests to be merged, before merging this one

- [x] iLCSoft/MarlinDD4hep#4
- [x] iLCSoft/MarlinTrkProcessors#9

**Review by andresailer — APPROVED** [review]

**Comment by andresailer** [comment]
@gaede merge this as well?

**Pull request merged**
